# Generated by Django 3.0.8 on 2020-07-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Página principal'),
        ),
    ]
